#' Predict using the knn1_twdtw model
#'
#' This function predicts the classes of new data using the Time Warped Dynamic Time Warping (TWDTW) 
#' method with a 1-nearest neighbor approach. The prediction is based on the minimum TWDTW distance 
#' to the known patterns stored in the `knn1_twdtw` model.
#'
#' @param object A `knn1_twdtw` model object generated by the `knn1_twdtw` function.
#' @param newdata A data frame or similar object containing the new observations 
#' (time series data) to be predicted.
#' @param ... Additional arguments passed to the \link[twdtw]{twdtw} function.
#'
#' @return A vector of predicted classes for the `newdata`.
#'
#' @seealso knn1_twdtw
#'
#' @inherit knn1_twdtw examples
#'
#' @export
predict.knn1_twdtw <- function(object, newdata, ...){


  # Convert newdata to time series
  newdata_ts <- prepare_time_series(newdata)

  # Compute TWDTW distances
  distances <- sapply(object$data$observations, function(pattern){
    sapply(newdata_ts$observations, function(ts) {
        proxy::dist(x = as.data.frame(ts), y = as.data.frame(pattern), method = "twdtw", ...)
    })
  })

  # Find the nearest neighbor for each observation in newdata
  nearest_neighbor <- apply(distances, 1, which.min)

  # Return the predicted label for each observation based on the nearest neighbor
  return(factor(object$data$label[nearest_neighbor]))
}
